---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: percona
  labels:
    name: percona
spec:
  replicas: 3
  selector: 
    matchLabels:
      name: percona 
  template: 
    metadata:
      labels: 
        name: percona
    spec:
      containers:
        - resources:
            limits:
              cpu: 0.5
          name: percona
          image: percona
          imagePullPolicy: IfNotPresent
          args:
            - "--ignore-db-dir"
            - "lost+found"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: k8sDem0
          ports:
            - containerPort: 3306
              name: percona
          volumeMounts:
            - mountPath: /var/lib/percona-mysql
              name: data-vol
      volumes:
        - name: data-vol
          persistentVolumeClaim:
            claimName: nfspvc
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: testclaim
# spec:
#   storageClassName: testclass
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5G
---
apiVersion: v1
kind: Service
metadata:
  name: percona-mysql
  labels:
    name: percona-mysql
spec:
  ports:
    - port: 3309
      targetPort: 3306
  selector:
      name: percona
