kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfspvc
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
