apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: nfspvc
  nfs:
    server: 10.43.254.47 # Update this nfs-server after applying the nfs service
    path: "/exports"
